### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by BenjaminT88** [BenjaminT88/Popo#4]
Finished User Auth with most of CSS

### Functional
- [x] login does not currently persist on refresh. Review bootstrapping the user to the window and your preloaded state in your entry file
- [x] Add a demo account button which logs in a demo user (used to allow recruiters to test without entering any details
- [ ] pre-fill the org_id with a demo account id for now (I know you plan on replacing this with a search once you have a seed file)

### Styling
- [x] Add a font-family to your reset file to ensure all fonts match those that appear on your login form
- [x] remove margin from body so that your navbar extends to the full width of the window

**Comment by minucos** [comment]
Hi mate

Looking good! Added a couple quick notes to the issue with some adjustments.

Let me know if you need any clarification on them, thanks!

Andy

**Comment by BenjaminT88** [comment]
Hi Andy,

I made the changes to everything other than pre-filling org_id because that's part of my next mvp. I'll seed some accounts data and make some accounts 'organization true'. Then I'll create a dropdown menu for org_id.
